### ISSUE TITLE
Extend response body text box area

### ISSUE THREAD

**Issue by duc-bhcoe** [jellydn/vscode-hurl-runner#38]
Thank you for the hard work on the Hurl toolset so far! I've really enjoyed using the nvim integration, but now I'm transitioning to VSCode for better team collaboration. The VSCode extension is quite solid compared to others on the market.

One feature that would be great to add is an expanded display area for the response body, especially when it’s an array of objects.

![CleanShot 2024-11-04 at 10 00 51@2x](https://github.com/user-attachments/assets/ddbacd78-6765-49e8-820f-cc630c68016f)

**Comment by jellydn** [comment]
Closed by #bd6513e73412e93be95568a2b191297447ed11df
